export default () => ({
    package: [],
    payment: [],
    purchase: [],
    lockedPackage: "",
    iFullName:"",
    iTaxOffice:"",
    iTaxNumber:"",
    iDate: new Date(Date.now()),
    iDesc:"Eğitim Hizmeti Bedeli",
    iQuantity:"1",
    iFee:"0",
    ia1:"",
    ia2:"",
    ia3:"",
    iUserId:"",
  });
